[package]
name = "parser-cli"
version = "0.1.0"
authors = ["Marcin Biernat <mb@marcinbiernat.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clippings-parser = { path = "../parser" }
